export const HOUSEHOLD_LIST_REQUEST = "HOUSEHOLD_LIST_REQUEST";
export const HOUSEHOLD_LIST_SUCCESS = "HOUSEHOLD_LIST_SUCCESS";
export const HOUSEHOLD_LIST_FAILURE = "HOUSEHOLD_LIST_FAILURE";

export const HOUSEHOLD_DETAILS_REQUEST = "HOUSEHOLD_DETAILS_REQUEST";
export const HOUSEHOLD_DETAILS_SUCCESS = "HOUSEHOLD_DETAILS_SUCCESS";
export const HOUSEHOLD_DETAILS_FAILURE = "HOUSEHOLD_DETAILS_FAILURE";

export const HOUSEHOLD_ADD_ORDER_REQUEST = "HOUSEHOLD_ADD_ORDER_REQUEST";
export const HOUSEHOLD_ADD_ORDER_SUCCESS = "HOUSEHOLD_ADD_ORDER_SUCCESS";
export const HOUSEHOLD_ADD_ORDER_FAILURE = "HOUSEHOLD_ADD_ORDER_FAILURE";
